# Generated by Django 2.2.3 on 2019-07-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190723_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='me',
            new_name='user',
        ),
    ]
