# Generated by Django 2.2.3 on 2019-07-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190723_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='avatar',
            field=models.ImageField(blank=True, default='images/error.png', upload_to='images/'),
        ),
    ]
